### ISSUE TITLE
Understanding and debugging dual infeasible models

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#428]
One of the most confusing modeling errors that new GPkit users experience is dual infeasibility (which also often shows up in cvxopt as a rank error).

The goal of this ticket is to explore whether there are simple diagnostics we could compute on the GP's A matrix to report more useful information to the user about _why_ the model is dual infeasible.

We currently only print warnings for variables that have no pressure in a certain direction. But more complicated dual infeasibility problems can arise, as in the following example:

``` python
from gpkit import Variable, Model


class Performance(Model):
    """flight power relations"""
    def setup(self):
        P = Variable("P", units="W", label="flight power")
        S = Variable("S", units="m^2", label="wing area")
        eta_p = Variable(r"\eta_p", value=0.75, label="motor+prop efficiency")
        L15D = Variable(r"C_L^{1.5}/C_D", value=25, label="power parameter")
        rho = Variable(r"\rho", units="kg/m^3", value=0.238,
                       label="air density")
        W = Variable("W", units="N", label="weight")

        return (P/W*S,
                [P/S >= 1/eta_p/L15D*(2/rho)**0.5*(W/S)**1.5])


if __name__ == "__main__":
    p = Performance()
    p.solve(solver="mosek")
```

The output does report the dual infeasibility issue:

```
Using solver 'mosek'
Solving for 3 variables.
Solving took 0.0116 seconds.
/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/geometric_program.py:152: RuntimeWarning: overflow encountered in exp
  np.exp(primal)))
Traceback (most recent call last):
  File "gpkit/models/aircraft/solar_uav.py", line 21, in <module>
    p.solve(solver="mosek")
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/model.py", line 206, in solve
    *args, **kwargs)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/model.py", line 350, in _solve
    result = solvefn(*args, **kwargs)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/geometric_program.py", line 189, in solve
    "\n\nThe infeasible solve's result is stored"
RuntimeWarning: final status of solver 'mosek' was 'DUAL_INFEAS_CER', not 'optimal'.

The infeasible solve's result is stored in the 'result' attribute
(model.program.result) and its raw output in 'solver_out'.

If the problem was Primal Infeasible, you can generate a feasibility-finding relaxation of your
Model with model.feasibility().
```

... but this isn't immediately helpful in helping to understand _why_ the model is dual infeasible. And the `model.feasibiliy()` suggestion is a distraction.

the cvxopt output is even less helpful:

```
Using solver 'cvxopt'
Solving for 3 variables.
Traceback (most recent call last):
  File "gpkit/models/aircraft/solar_uav.py", line 21, in <module>
    p.solve()
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/model.py", line 206, in solve
    *args, **kwargs)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/model.py", line 350, in _solve
    result = solvefn(*args, **kwargs)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/geometric_program.py", line 137, in solve
    k=self.k, *args, **kwargs)
  File "/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/_cvxopt.py", line 42, in cvxoptimize
    solution = gpsolver(k, F, g)
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/cvxprog.py", line 2162, in gp
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/cvxprog.py", line 1969, in cp
  File "build/bdist.macosx-10.5-x86_64/egg/cvxopt/cvxprog.py", line 788, in cpl
ValueError: Rank(A) < p or Rank([H(x); A; Df(x); G]) < n
```

The first step is for us to understand deeply why this problem is dual infeasible -- from both a primal and dual perspective.

**Comment by bqpd** [comment]
Addressed by #842

**Comment by whoburg** [comment]
#894 addresses the bit about a misleading error message, but I don't think the intent of this ticket is fully resolved.

How about using the MWE at the top to document BoundedConstraintSets or the new debug method?

**Comment by bqpd** [comment]
The new debug method handles this well!

```
In [7]: _ = p.debug()
Debugging...
_____________________
Using solver 'cvxopt'
Solving for 9 variables.
Solving took 0.037 seconds.

Feasible with these variables bounded:
 sensitive to lower bound: [S_Performance, P_Performance]
   value near lower bound: [S_Performance, P_Performance, W_Performance]

_____________________
Using solver 'cvxopt'
Solving for 4 variables.

Model does not solve with relaxed constraints.
_____________________
```

**Comment by whoburg** [comment]
cool!

still curious about connections between debug and things we can compute directly from the A matrix, but agree that this is closed for now!
