### ISSUE TITLE
The definition of insanity is doing the same thing over and over and......

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#435]
I don't really know how to explain or reproduce this, but cvxopt appears to be temperamental. Specifically there are times when it solves a problem just fine once then returns unsolved after 52 iterations the next time for the *exact same problem*. I thought I had noticed this happening but assumed I was going crazy. I just ran the same problem twice in a row in quick succession without changing anything in between.

Any ideas what is going on?

```
[philippekirschen@dhcp-18-189-55-193 landing_gear]$ /usr/bin/python landing_gear.py
Optional Python units library (Pint) not installed; unit support disabled.
Beginning signomial solve.
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
Solving took 9 GP solves and 1.52 seconds.

Cost
----
 249.1

Free Variables
--------------
          B_LandingGear : 15.75      [m] 
L_{m_{max}}_LandingGear : 6.946e+05  [N] 
L_{n_{dyn}}_LandingGear : 7.125e+04  [N] 
L_{n_{max}}_LandingGear : 1.609e+05  [N] 
L_{n_{min}}_LandingGear : 8.03e+04   [N] 
          T_LandingGear : 5.72       [m] 
     W_{lg}_LandingGear : 249.1      [N] 
     W_{mg}_LandingGear : 186.7      [N] 
     W_{ms}_LandingGear : 77.8       [N] 
     W_{mw}_LandingGear : 15.56      [N] 
     W_{ng}_LandingGear : 62.4       [N] 
     W_{ns}_LandingGear : 52         [N] 
     W_{nw}_LandingGear : 10.4       [N] 
        l_m_LandingGear : 2.5        [m] 
        l_n_LandingGear : 2.5        [m] 
        r_m_LandingGear : 0.0151     [m] 
        r_n_LandingGear : 0.01234    [m] 
        x_m_LandingGear : 20.15      [m] 
        x_n_LandingGear : 4.4        [m] 
      xca_m_LandingGear : 1.572      [m] 
      xcf_m_LandingGear : 3.15       [m] 

Constants
---------
              N_s_LandingGear : 2          [-]      
              W_0_LandingGear : 8.044e+05  [N]      
       \tan(\phi)_LandingGear : 0.2679     [-]      
\tan(\theta_{TO})_LandingGear : 0.2679     [-]      
      d_{nacelle}_LandingGear : 2          [m]      
                g_LandingGear : 9.81       [m/s^2]  
      h_{nacelle}_LandingGear : 0.5        [m]      
           n_{mg}_LandingGear : 2          [-]      
           rho_Ti_LandingGear : 4430       [kg/m^3] 
          sig_y_c_LandingGear : 9.7e+08    [Pa]     
         x_{CG_a}_LandingGear : 18         [m]      
         x_{CG_f}_LandingGear : 17         [m]      
        x_{upswp}_LandingGear : 28         [m]      
            xca_n_LandingGear : 13.6       [m]      
            xcf_n_LandingGear : 12.6       [m]      
              y_m_LandingGear : 2.86       [m]      
           z_{CG}_LandingGear : 2          [m]      

Sensitivities
-------------
 x_{CG_f}_LandingGear : -2 
x_{upswp}_LandingGear : 1  
    xcf_n_LandingGear : 1  

[philippekirschen@dhcp-18-189-55-193 landing_gear]$ /usr/bin/python landing_gear.py
Optional Python units library (Pint) not installed; unit support disabled.
Beginning signomial solve.
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
W_{lg}_LandingGear has no upper bound
Traceback (most recent call last):
  File "landing_gear.py", line 154, in <module>
    LandingGear().test()
  File "landing_gear.py", line 148, in test
    sol = self.localsolve()
  File "/Library/Python/2.7/site-packages/gpkit/model.py", line 247, in localsolve
    *args, **kwargs)
  File "/Library/Python/2.7/site-packages/gpkit/model.py", line 350, in _solve
    result = solvefn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gpkit/signomial_program.py", line 116, in localsolve
    calling .localsolve(..., iteration_limit=NEWLIMIT).""" % len(self.gps))
RuntimeWarning: problem unsolved after 52 iterations.

    The last result is available in Model.program.gps[-1].result. If the gps
    appear to be converging, you may wish to increase the iteration limit by
    calling .localsolve(..., iteration_limit=NEWLIMIT).
```

Source can be found at: https://github.mit.edu/convex/GPjet/commit/bbd33f62f4f30fc2da6ae395c817c5f14e08d091

**Comment by pgkirsch** [comment]
Huh, after the second attempt, the code continue to return unsolved, BUT, if I change the code back to something I know works, save it, run it, fast forward to the temperamental code again, save it, run it, it solves the problem, but this time in 31 iterations. Is it just chattering around in the numerical tolerance? How are these solvers not deterministic?

**Comment by pgkirsch** [comment]
When I copy this file onto my desktop and solve using mosek I get an exp(primal) overflow warning.

**Comment by whoburg** [comment]
@bqpd are you planning to debug this?

I think a first step could be to try to reproduce the problem for a GP only -- i.e. try to get cvxopt to return different solutions to the same GP (and understand why they're different). Then, we can try to understand whether different solutions to on of the GP's solved during the SP convergence leads to a different SP convergence path (or to no convergence at all).

**Comment by bqpd** [comment]
Yeah. I'm betting there's some state in either SignomialProgram or Model that's causing this...and if it happens with GPs too, that reduces it to a Model fault.

**Comment by whoburg** [comment]
sounds good!

**Comment by pgkirsch** [comment]
Notes (to self) about something I tried:
Solved the SP in question twice. One time it solved in 32 iterations, the other in 12. I compared the `m.program.gps` list for both solves.

GPs 0 - 9 and N-1 and N are identical. Obviously the first had 20 GPs sandwiched in between.

I took that 10th GP and solved it alone repeatedly to see if it was nondeterministic but sure enough it gives the same answer every time.

If it isn't non-deterministic why would the SP vary at that point in the solve?

**Comment by bqpd** [comment]
(sounds like a bug in SignomialProgram...)

**Comment by whoburg** [comment]
sounds like a great start at debugging!

**Comment by bqpd** [comment]
This may have been the substitution bug we were seeing this week, but it's antiquated enough that it's difficult to tell.

**Comment by whoburg** [comment]
huh, I just checked out the commit referenced above and ran `landing_gear.py` with the latest master; I now get 

`ValueError: Model valid as a Geometric Program.`
