### ISSUE TITLE
Tight constraint throwing error in solved signomial program

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#734]
in my engine model I wrapped all inequality constraints in a TCS. The SP solved but the following error occurred 

Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\aircraft\engine.py", line 74, in <module>
    sol = engine.localsolve(verbosity = 4, kktsolver="ldl")
  File "C:\Python27\lib\site-packages\gpkit\constraints\prog_factories.py", line 80, in solvefn
    result = solvefn(solver, verbosity-1, *args, **kwargs)
  File "C:\Python27\lib\site-packages\gpkit\constraints\signomial_program.py", line 129, in localsolve
    self.process_result(result)
  File "C:\Python27\lib\site-packages\gpkit\constraints\set.py", line 236, in process_result
    constraint.process_result(result)
  File "C:\Python27\lib\site-packages\gpkit\constraints\set.py", line 236, in process_result
    constraint.process_result(result)
  File "C:\Python27\lib\site-packages\gpkit\constraints\linked.py", line 71, in process_result
    super(LinkedConstraintSet, self).process_result(result)
  File "C:\Python27\lib\site-packages\gpkit\constraints\set.py", line 236, in process_result
    constraint.process_result(result)
  File "C:\Python27\lib\site-packages\gpkit\constraints\set.py", line 236, in process_result
    constraint.process_result(result)
  File "C:\Python27\lib\site-packages\gpkit\constraints\set.py", line 236, in process_result
    constraint.process_result(result)
  File "C:\Python27\lib\site-packages\gpkit\constraints\tight.py", line 23, in process_result
    leftsubbed = constraint.left.sub(variables).value
  File "C:\Python27\lib\site-packages\gpkit\nomials\nomial_math.py", line 215, in sub
    return Signomial(exps, cs, require_positive=require_positive)
  File "C:\Python27\lib\site-packages\gpkit\nomials\nomial_math.py", line 112, in __init__
    raise ValueError("each c must be positive.")
ValueError: each c must be positive.

looks like even thought I have signomials enabled nomial_math isn't seeing that

the commit that throws the error is 	be60790 in https://github.com/hoburg/gpkit-models/pull/72#issuecomment-224971711

**Comment by whoburg** [comment]
@bqpd do you have time to take a quick look at this? We need it resolved for a presentation Mon.

@mayork if you could share the location of the model and code to reproduce this, that would help.

I can't look today but can take a look Sun if @bqpd can't.

**Comment by mayork** [comment]
@whoburg @bqpd this one isn't that time sensitive, I can just remove TCS from the code to run it

@whoburg I realized I didn't make an issue for the bug I mentioned yesterday. I think I found a work around, so we should be good to go for Monday. I'll still create an issue for the error.

**Comment by mayork** [comment]
I'm not sure what the proper technical verbiage is, but if this fix could be added to the current release that  would be awesome, I think it would help debug the engine code

**Comment by bqpd** [comment]
It's waiting on @whoburg's review, but you can check the branch out locally
and use it!

**Comment by mayork** [comment]
Oh yeah that was all I wanted to do. This is goingto be a really amateur question but how do I see what branch it's on? I tried to see if it was a branch but I thought it wasn't since it's not a pull request...

**Comment by bqpd** [comment]
Ah, if you click on the commit number above (38714f932a396c788954f1464d7b5be98899c4e6) it says at the top that it's on the fixdes branch, which is currently PR #743

**Comment by mayork** [comment]
Okay awesome thanks!
