### ISSUE TITLE
Nomial Math Error

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#739]
@bqpd @whoburg this is the more pressing error. It occurs in commit 	4cce8f5 (labeled nomial math error) of the engine code at https://github.com/hoburg/gpkit-models/pull/72. Run the engine component testing script and the compressor map throws the error...more precisely this line (568) throws the error TCS([((mtilds-mtild)/.03) <= te_exp_minus1(z, nterm=3)]). It doesn't matter if it's a tight constraint set or not. If the <= goes to a >= the error goes away. I'm guessing it has to do with the te_exp_minus1 but can't really tell.

Here's the error

Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\aircraft\engine_component_testing.py", line 122, in <module>
    compmap.solve(kktsolver="ldl", verbosity = 4)
  File "C:\Python27\lib\site-packages\gpkit\constraints\prog_factories.py", line 79, in solvefn
    self.program, solvefn = genfunction(self, verbosity-1)
  File "C:\Python27\lib\site-packages\gpkit\constraints\prog_factories.py", line 34, in programify
    prog = program(self.cost, self, substitutions, verbosity, **kwargs)
  File "C:\Python27\lib\site-packages\gpkit\geometric_program.py", line 68, in __init__
    constr_posys = constraint.as_posyslt1()
  File "C:\Python27\lib\site-packages\gpkit\constraints\set.py", line 149, in as_posyslt1
    posys = constraint.as_posyslt1()
  File "C:\Python27\lib\site-packages\gpkit\nomials\nomial_math.py", line 691, in as_posyslt1
    raise TypeError("SignomialInequality could not simplify to"
TypeError: SignomialInequality could not simplify to a PosynomialInequality

**Comment by mayork** [comment]
I'm an idiot sorry guys. I didn't realize I was calling solve twice and only once did I call localsolve....

**Comment by bqpd** [comment]
No worries! I think this is still a bug, it could have given a clearer
error message.
