### ISSUE TITLE
apparent bug in sensitivity code

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#763]
I just ran a test case and it solved but the solution table didn't print due to this key error

```
Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\Commercial Sizing\Commerical_Flight_Profile.py", line 530, in <module>
    sol = m.localsolve(kktsolver = "ldl", verbosity = 4)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\prog_factories.py", line 80, in solvefn
    result = solvefn(solver, verbosity-1, *args, **kwargs)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\signomial_program.py", line 128, in localsolve
    result["sensitivities"]["constants"])
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 218, in sens_from_gpconstr
    constr_sens[str(c)] = c.sens_from_gpconstr(gpa, gp_s, var_senss)
  File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\nomial_math.py", line 714, in sens_from_gpconstr
    constr_sens[str(negy)] = pa_sens["overall"]
KeyError: 'overall'
```

looks like a possible bug in the sensitivity code

the commit that resulted in this is https://github.com/hoburg/gpkit-models/pull/73/commits/5ce9cbead7c10ca4351213beda4b2d7992c0756d

**Comment by mayork** [comment]
I believe this only happens when I create a model partially composed of two of the same submodels, like below where I created two engine on design models
```
#define all the submodels
        cmc = CommericalMissionConstraints(0)
        climb1 = Climb1()
        climb2 = Climb2()
        cruise2 = Cruise2()
        atm = Atmosphere(Nseg)
        eonD = EngineOnDesign()
        eoffD = EngineOffDesign()
        eonD2 = EngineOnDesign()
        
        substitutions = {      
            'W_{e}': 44000*9.8*units('N'),
           ...
            '\pi_{hc_D}': 10
            }
        self.submodels = [cmc, climb1, climb2, cruise2, eonD, eonD2]

        constraints = ConstraintSet([self.submodels])

        constraints.subinplace({'TSFC_{cr21}_Cruise2': 'TSFC_E_EngineOnDesign', 'TSFC_{cr22}_Cruise2': 'TSFC_E_EngineOffDesign',
                                'D2_Cruise2': 'F_{spec_EngineOffDesign'})

        lc = LinkedConstraintSet(constraints, exclude={...'})

        Model.__init__(self, cmc.cost, lc, substitutions, **kwargs)
```

**Comment by bqpd** [comment]
Any Signomial Equalities in this?

**Comment by mayork** [comment]
yeah I'm pretty sure its 2 per engine model. However, i just started making new engine classes with different names and I can run without a problem

**Comment by bqpd** [comment]
Oh dear. Will investigate.

**Comment by bqpd** [comment]
Fixed for now by not having constraint sensitivities.
