### ISSUE TITLE
Post Solve ndarray error

### ISSUE THREAD

**Issue by bjarni177** [hoburg/gpkit#929]
Optimal solution found.
Solving took 0.173 seconds.
result packing took 8.2% of solve time
solution checking took 1.6% of solve time
Solving took 4 GP solves and 1.59 seconds.
Traceback (most recent call last):
  File "/Users/Bjarni/Documents/GitHub/gpkit-models/gpkitmodels/aircraft/fuselage.py", line 664, in <module>
    sol = Fuselage.test(fuselage_type = 'narrowbody')
  File "/Users/Bjarni/Documents/GitHub/gpkit-models/gpkitmodels/aircraft/fuselage.py", line 546, in test
    return fu.localsolve(solver = None, verbosity=4)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/prog_factories.py", line 92, in solvefn
    self.process_solution(solution)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/set.py", line 287, in process_solution
    constraint.process_solution(sol)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/set.py", line 287, in process_solution
    constraint.process_solution(sol)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/tight.py", line 31, in process_solution
    negy = negy.sub(variables).value
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/nomial_math.py", line 215, in sub
    _, exps, cs, _ = substitution(self, substitutions)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/substitution.py", line 197, in substitution
    " of type '%s'" % (var, type(sub)))
TypeError: could not substitute w_{floor}_Fuselage with value of type '<type 'numpy.ndarray'>'
[Finished in 5.1s with exit code 1]

**Comment by mayork** [comment]
this was on `feasmod` branch right?

**Comment by bjarni177** [comment]
on the feassweep branch

**Comment by mayork** [comment]
I'm also getting a post solve error on the `feassweep` branch. The commit is https://github.com/hoburg/gpkit-models/pull/94/commits/686e42dbe0d825520124cc7ec6cbedeb9cfb0d1f

and the error traceback is 

```
Traceback (most recent call last):
  File "/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/Commerical_Flight_Profile_Simple_Performance.py", line 607, in <module>
    bounds, sol = m.determine_unbounded_variables(m, solver="mosek",verbosity=4, iteration_limit=100)
  File "/Users/mayork/Documents/GpGit/gpkit-models/gpkitmodels/Commercial Sizing/Commerical_Flight_Profile_Simple_Performance.py", line 561, in determine_unbounded_variables
    sol = m.solve(solver, verbosity, **kwargs)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/prog_factories.py", line 80, in solvefn
    result = solvefn(solver, verbosity, *args, **kwargs)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/geometric_program.py", line 191, in solve
    result = self._compile_result(solver_out)  # NOTE: SIDE EFFECTS
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/geometric_program.py", line 277, in _compile_result
    p_var_senss = constr.sens_from_dual(las, nus)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.py", line 260, in sens_from_dual
    v_ss = constr.sens_from_dual(la, nu)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.py", line 260, in sens_from_dual
    v_ss = constr.sens_from_dual(la, nu)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/constraints/set.py", line 260, in sens_from_dual
    v_ss = constr.sens_from_dual(la, nu)
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.py", line 646, in sens_from_dual
    for (var, locs) in presub.varlocs.items()
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/nomials/nomial_math.py", line 647, in <dictcomp>
    if var in self._last_used_substitutions}
  File "/Users/mayork/Documents/GpGit/gpkit/gpkit/keydict.py", line 86, in __contains__
    return not np.isnan(dict.__getitem__(self, key)[idx])
TypeError: 'float' object has no attribute '__getitem__'
```

**Comment by bqpd** [comment]
@bjarni177, should be fixed on the `feassweep` branch. Close this issue if it is!

**Comment by bqpd** [comment]
@bjarni177, going to assume this is now working...

**Comment by bjarni177** [comment]
We should be good :)
